title: Coding Blog
author: Jordy Pereira
email: me@jordypereira.be
description: > # this means to ignore newlines until "baseurl:"
 Here I will talk about my experiences as a web developer and the things I go through.
 
 Sometimes they will be useful and sometimes they will be funny.

# social links
twitter_username: _perjor
github_username:  perjor

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
